### ISSUE TITLE
RunFromALM throws error

### ISSUE THREAD

**Issue by dascalos** [hpsa/ADM-TFS-Extension#13]
Trying to run tests using the RunFromALM plugin.  I eventually get the output below.  I have logged in as the build user and installed TDConnectivity as suggested by the error message.  

I've also opened up the specified directory permissions to everyone all rights.

Help is greatly appreciated.

`2017-10-27T15:38:13.5356641Z ##[section]Starting: RunFromALM: 
2017-10-27T15:38:13.5512861Z ==============================================================================
2017-10-27T15:38:13.5512861Z Task         : UFT ALM Execution
2017-10-27T15:38:13.5512861Z Description  : Execute UFT tests from ALM
2017-10-27T15:38:13.5512861Z Version      : 1.0.0
2017-10-27T15:38:13.5512861Z Author       : 
2017-10-27T15:38:13.5512861Z Help         : 
2017-10-27T15:38:13.5512861Z ==============================================================================
2017-10-27T15:38:13.5825398Z Preparing task execution handler.
2017-10-27T15:38:14.3950497Z Executing the powershell script: E:\devagent\Agent1\_work\_tasks\RunFromALM_a571ae7c-e100-42e1-8ced-498b46029770\1.0.0\localTask.ps1
2017-10-27T15:38:14.3950497Z "Started..."
2017-10-27T15:38:14.3950497Z Timeout is set to: -1
2017-10-27T15:38:14.3950497Z Run mode is set to: RUN_LOCAL
2017-10-27T15:38:15.9575798Z ============================================================================
2017-10-27T15:38:15.9575798Z Starting test set execution
2017-10-27T15:38:15.9732010Z Test set name: CI_Test_Set_for_Dascalos, Test set id: 803
2017-10-27T15:39:16.1081720Z Could not create scheduler, please verify ALM client installation on run machine by downloading and in installing the add-in form: http://daycrtqc04:8080/qcbin/TDConnectivity_index.html
2017-10-27T15:39:17.4050579Z ##[error]System.IO.FileNotFoundException: Could not find file 'C:\admtfs\UFTWorking\res\Results27102017113813SSS.xml'.
2017-10-27T15:39:17.4050579Z File name: 'C:\admtfs\UFTWorking\res\Results27102017113813SSS.xml'
2017-10-27T15:39:17.4050579Z    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2017-10-27T15:39:17.4050579Z    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2017-10-27T15:39:17.4050579Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2017-10-27T15:39:17.4050579Z    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
2017-10-27T15:39:17.4050579Z    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
2017-10-27T15:39:17.4050579Z    at PSModule.AbstractLauncherTaskCmdlet.CollateResults(String resultFile, String log, String resdir)
2017-10-27T15:39:17.4050579Z    at PSModule.AbstractLauncherTaskCmdlet.ProcessRecord()
2017-10-27T15:39:17.4206802Z ##[error]PowerShell script completed with 1 errors.
2017-10-27T15:39:17.4206802Z ##[section]Finishing: RunFromALM: `

**Comment by dascalos** [comment]
Got it.  Found in the source we needed to run...
http://almbox:8080/qcbin/start_a.jsp?common=true
