### ISSUE TITLE
RunFromALM throws an error "System.IO.FileNotFoundException: The specified module '\bin\PSModule.dll' was not loaded because no valid module file was found in any module directory."

### ISSUE THREAD

**Issue by YasodhaNithi** [hpsa/ADM-TFS-Extension#21]
In "RunFromALM" build step, the below error is displaying continuously.

2019-01-16T07:47:31.9549824Z ##[section]Starting: RunFromALM: 
2019-01-16T07:47:31.9553421Z ==============================================================================
2019-01-16T07:47:31.9553500Z Task         : UFT ALM Execution
2019-01-16T07:47:31.9553554Z Description  : Execute UFT tests from ALM
2019-01-16T07:47:31.9553625Z Version      : 1.0.0
2019-01-16T07:47:31.9553674Z Author       : 
2019-01-16T07:47:31.9553721Z Help         : 
2019-01-16T07:47:31.9553792Z ==============================================================================
2019-01-16T07:47:31.9684816Z Preparing task execution handler.
2019-01-16T07:47:47.2628062Z Executing the powershell script: D:\a\_tasks\RunFromALM_a571ae7c-e100-42e1-8ced-498b46029770\1.0.0\localTask.ps1
2019-01-16T07:47:48.0405346Z ##[error]System.IO.FileNotFoundException: The specified module '\bin\PSModule.dll' was not loaded because no valid module file was found in any module directory.
2019-01-16T07:47:48.1774166Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:48.1774525Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:48.1774646Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:48.1774734Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1774842Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1774924Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1788346Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:48.1788615Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:48.1788730Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:48.1788816Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1788919Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1788993Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1795881Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:48.1796133Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:48.1796249Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:48.1796333Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1796434Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1796512Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1802096Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:48.1803484Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:48.1803602Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:48.1803686Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1804146Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:48.1804228Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1485766Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Invoke-RunFromAlmTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2019-01-16T07:47:59.1486164Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2019-01-16T07:47:59.1486277Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2019-01-16T07:47:59.1486369Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2019-01-16T07:47:59.1486458Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2019-01-16T07:47:59.1486587Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:59.1486670Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1486761Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1506004Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:59.1506314Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:59.1506416Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:59.1506529Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1506604Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1506695Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1510607Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null.
2019-01-16T07:47:59.1510871Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:59.1510970Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:59.1511578Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1511653Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1689689Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:59.1689979Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:59.1690294Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:59.1690420Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1690497Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1690591Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1693621Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2019-01-16T07:47:59.1693884Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2019-01-16T07:47:59.1694015Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-01-16T07:47:59.1694107Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1694197Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.1694272Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T07:47:59.2726426Z ##[error]PowerShell script completed with 10 errors.
2019-01-16T07:47:59.2733994Z ##[section]Finishing: RunFromALM:

**Comment by JagsChandra** [comment]
> In "RunFromALM" build step, the below error is displaying continuously.
> 
> 2019-01-16T07:47:31.9549824Z ##[section]Starting: RunFromALM:
> 2019-01-16T07:47:31.9553421Z ==============================================================================
> 2019-01-16T07:47:31.9553500Z Task : UFT ALM Execution
> 2019-01-16T07:47:31.9553554Z Description : Execute UFT tests from ALM
> 2019-01-16T07:47:31.9553625Z Version : 1.0.0
> 2019-01-16T07:47:31.9553674Z Author :
> 2019-01-16T07:47:31.9553721Z Help :
> 2019-01-16T07:47:31.9553792Z ==============================================================================
> 2019-01-16T07:47:31.9684816Z Preparing task execution handler.
> 2019-01-16T07:47:47.2628062Z Executing the powershell script: D:\a_tasks\RunFromALM_a571ae7c-e100-42e1-8ced-498b46029770\1.0.0\localTask.ps1
> 2019-01-16T07:47:48.0405346Z ##[error]System.IO.FileNotFoundException: The specified module '\bin\PSModule.dll' was not loaded because no valid module file was found in any module directory.
> 2019-01-16T07:47:48.1774166Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
> 2019-01-16T07:47:48.1774525Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
> 2019-01-16T07:47:48.1774646Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> 2019-01-16T07:47:48.1774734Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1774842Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1774924Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1788346Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null. 2019-01-16T07:47:48.1788615Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate) 2019-01-16T07:47:48.1788730Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) 2019-01-16T07:47:48.1788816Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2019-01-16T07:47:48.1788919Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:48.1788993Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:48.1795881Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
> 2019-01-16T07:47:48.1796133Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
> 2019-01-16T07:47:48.1796249Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> 2019-01-16T07:47:48.1796333Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1796434Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1796512Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:48.1802096Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null. 2019-01-16T07:47:48.1803484Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate) 2019-01-16T07:47:48.1803602Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) 2019-01-16T07:47:48.1803686Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2019-01-16T07:47:48.1804146Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:48.1804228Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1485766Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Invoke-RunFromAlmTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 2019-01-16T07:47:59.1486164Z at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
> 2019-01-16T07:47:59.1486277Z at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope) 2019-01-16T07:47:59.1486369Z at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource) 2019-01-16T07:47:59.1486458Z at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context) 2019-01-16T07:47:59.1486587Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) 2019-01-16T07:47:59.1486670Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1486761Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1506004Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
> 2019-01-16T07:47:59.1506314Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
> 2019-01-16T07:47:59.1506416Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> 2019-01-16T07:47:59.1506529Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1506604Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1506695Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1510607Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Message' because it is null. 2019-01-16T07:47:59.1510871Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate) 2019-01-16T07:47:59.1510970Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) 2019-01-16T07:47:59.1511578Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1511653Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1689689Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
> 2019-01-16T07:47:59.1689979Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
> 2019-01-16T07:47:59.1690294Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> 2019-01-16T07:47:59.1690420Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1690497Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1690591Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) 2019-01-16T07:47:59.1693621Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null. 2019-01-16T07:47:59.1693884Z at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate) 2019-01-16T07:47:59.1694015Z at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) 2019-01-16T07:47:59.1694107Z at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1694197Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.1694272Z at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2019-01-16T07:47:59.2726426Z ##[error]PowerShell script completed with 10 errors.
> 2019-01-16T07:47:59.2733994Z ##[section]Finishing: RunFromALM:

Were you able to resolve this errror

**Comment by rick-jordan** [comment]
Hello Guys. 
Here I am having the same problem all the time ... 
When entered on RunFromFileSystemTask I get the error:

Starting: RunFromFileSystemTask
******************************************************************************
==============================================================================
Task         : UFT File System Execution
Description  : Execute UFT tests from file system
Version      : 1.0.4
Author       : 
Help         : 
==============================================================================
Task 'RunFromFileSystemTask' (1.0.4) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.
Executing the powershell script: D:\TFSAgents\CS43\1\_work\_tasks\RunFromFileSystemTask_cfbe1493-3bb1-44d5-ac87-7f14a148a6f2\1.0.4\localTask.ps1
**System.IO.FileNotFoundException: The specified module '\bin\PSModule.dll' was not loaded because no valid module file was found in any module directory.
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.**

I don't have any more ideas how to get rid of this .... :| some help would be appreciated ....

**Comment by shankarvrp** [comment]
You should be able to fix it with either of these

1) Provide adequate permissions to the user running the agent
2) If some cases, you will have to "unblock" all the files under bin (DLLs) (right click-Properties-unblock)

HTH

**Comment by shankarvrp** [comment]
You should be able to fix it with either of these

- Provide adequate permissions to the folder, for the user running the agent (entire agent folder)
- If some cases, you will have to "unblock" all the files under bin (DLLs) (right click-Properties-unblock)
- Once you do either or above or both, delete the tasks under _work/_tasks folder. Stop and Start the agent and it should get it working

HTH
